rankPopularity, From: 2 

Edge inserted:  2 -> 7 
Edge inserted:  1 -> 6 
Edge inserted:  4 -> 2 
Edge inserted:  2 -> 5 
Edge inserted:  5 -> 4 
Edge inserted:  1 -> 4 
Edge inserted:  1 -> 2 
Edge inserted:  2 -> 1 


rankPopularity: 
 node: 1, rank:      0.333 
 node: 2, rank:      0.667 
 node: 4, rank:      2.000 
 node: 5, rank:      1.000 
 node: 6, rank:      2.000 
 node: 7, rank:      2.000 
 
